### ISSUE TITLE
Support for core-js 3+

### ISSUE THREAD

**Issue by venkatajanapareddy** [andreassolberg/jso#109]
Im using JSO in a Vue app built using vue-cli(v4.0.0) which has core-js (v3.3.2) as a dependency. But JSO is using core-js (v2.x.x). Hence , Im getting the following error. 

```
These dependencies were not found:

* core-js/fn/array/includes in ./node_modules/jso/src/JSO.js
* core-js/fn/object/assign in ./node_modules/jso/src/JSO.js
* core-js/fn/promise in ./node_modules/jso/src/JSO.js
```

**Comment by dosstx** [comment]
https://github.com/andreassolberg/jso/pull/99

**Comment by venkatajanapareddy** [comment]
@zenluv
