### ISSUE TITLE
Usage with own oAuth service

### ISSUE THREAD

**Issue by Ayame** [andreassolberg/jso#13]
This is not really an issue but rather a question. I need to implement oAuth in a PhoneGap application but with the customer's oAuth system (not facebook or any other known entity)
Is this possible as well with your library? 

Will this solution work on Android?

**Comment by andreassolberg** [comment]
Yes, that should be possible. At least if the custom oauth provider is following the OAuth 2.0 specification, and supports the implicit grant flow.
