### ISSUE TITLE
On Android 2.3.3 trying to parse null object causes exception on line 203

### ISSUE THREAD

**Issue by KristianDD** [andreassolberg/jso#18]
Not exactly a bug inside the library, but still can be safeguarded. This issue breaks my application on Android 2.3.3 devices :)
![2013-03-22_1553](https://f.cloud.github.com/assets/2412096/290964/2f9c5bdc-92f8-11e2-85b8-ed6005e136a6.png)

This should do the job.

``` javascript
    Api_default_storage.prototype.getTokens = function(provider) {
        // log("Get Tokens (" + provider+ ")");
        var localTokens = localStorage.getItem("tokens-" + provider),
            tokens = localTokens ? JSON.parse(localTokens) : [];

        log("Token received", tokens)
        return tokens;
    };
```

**Comment by andreassolberg** [comment]
Please reopen if this still is an issue with 4.x...
