### ISSUE TITLE
I believe that replacing addition symbol with a space is a bug in parseQueryString()

### ISSUE THREAD

**Issue by gcirne** [andreassolberg/jso#23]
When my access token has an addition symbol (+) the following line replaces it with a space, making my access token invalid:

https://github.com/andreassolberg/jso/blob/master/jso.js#L89

I believe this is bug. If it is, I can send a pull request.

**Comment by andreassolberg** [comment]
The latest version now uses `decodeURIComponent`, which I assume works correctly. Let me know if you still have issues with this.
