### ISSUE TITLE
Oauth.ajax should return a jqXHR object, or at least a promise object

### ISSUE THREAD

**Issue by rjmackay** [andreassolberg/jso#24]
I'm using jso2 with backboneJS, I've overridden Backbone.ajax with Oauth.ajax.
This works perfectly.. except it just returns undefined, not a jqxhr object as it would normally.. 

This isn't 'breaking' anything I can find yet, but its making it very hard to manage multiple async calls in a sane way..

**Comment by andreassolberg** [comment]
The jquery ajax() wrapper is removed in 4.x branch, but I'm considering to re-add it. When I do, I'll makre sure to check this issue.

**Comment by andreassolberg** [comment]
I've re-added an jquery ajax() wrapper. But for various reasons, I am adding a promise-based response. Look for `FetcherJQuery` in the Readme.
