### ISSUE TITLE
Cross Domain 

### ISSUE THREAD

**Issue by SnigBhaumik** [andreassolberg/jso#29]
New to this library.
Is cross domain validation possible by this?

**Comment by leolems** [comment]
Cross domain depends on the server you want to reach, THEY should allow the request :question:

**Comment by andreassolberg** [comment]
This is true. It depends on the server you would like to reach. I would recommend enabling CORS on an oauth protected API server as best practice.

Here is how you enable CORS:

http://enable-cors.org
