### ISSUE TITLE
response_type fixed to token!

### ISSUE THREAD

**Issue by mcianc** [andreassolberg/jso#35]
Using Box.com i need to set response_type  to 'code' like specified in http://tools.ietf.org/html/rfc6749#section-4.1.1.

**Comment by werddomain** [comment]
comment on 23 Oct 2014 and no response?
Did you find a way to do it?

**Comment by RobertDeRose** [comment]
This is for implicit OAuth, http://tools.ietf.org/html/rfc6749#section-4.2.1

I hope one of you evenly figured that out. This issue should be closed.

**Comment by andreassolberg** [comment]
JSO used to support implicit grant flow only. We're heading towards supporting other flows, although the changes are 99% you should use implicit grant flow if you are using a webapp.
