### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by kevinconaway** [andreassolberg/jso#48]
@andreassolberg will you please clarify what license JSO is covered under?

The [LICENCE.md](https://github.com/andreassolberg/jso/blob/master/LICENCE.md) indicates BSD but the [README.md](https://github.com/andreassolberg/jso/blob/master/README.md) indicates LGPL

**Comment by andreassolberg** [comment]
Haha, thanks.
I've updated both to reflect GNU Lesser General Public License.
