### ISSUE TITLE
Documentation & examples

### ISSUE THREAD

**Issue by sebastiancarlsson** [andreassolberg/jso#51]
Are there any plans to provide more extensive documentation and examples? Under "Using JSO", besides the constructor there are 3 API calls, the documentation is at best cryptic and it is not mentioned at all how these are supposed to work together.

```javascript

//1.
jso.callback();

//2. what is opts?
jso.getToken(opts).
	then(function(token) {
			console.log("I got the token: ", token);
		});

//3.
jso.wipeTokens();
```

**Comment by maksimu** [comment]
I have the same questions. @sebastiancarlsson were you able to figure out the answer?

**Comment by macrojames** [comment]
It works with `opts = {}`
opts can have a property "allowredir".

**Comment by sebastiancarlsson** [comment]
(Sorry for extremely late reply @maksimu)

Thank you @macrojames, I dug into the source code and then decided to write my own implementation in the end, in order to understand fully every step of the authorisation process.
