### ISSUE TITLE
jso.js callback "broken" ??

### ISSUE THREAD

**Issue by kimamil** [andreassolberg/jso#55]
Hey there, thanks for this library. I am working my way through it for a seamless integration into my App. However I do have some issues with the entire providerId/state/scope thingy (pretty new to oAuth).

In addition I think there is a bug in the callback() function. In jso.js starting on line 1018:

```
/**
 * If state was not provided, and default provider contains a scope parameter
 * we assume this is the one requested...
 */
if (!atoken.state && co.scope) {
    state.scopes = instance._getRequestScopes();
    utils.log("Setting state: ", state);
}
```

But 'co' never gets defined anywhere ... :/ I haven't really worked through the code because I am still in an experimental phase. But from guessing I'd say this should be 'instance.scope' ??

**Comment by kimamil** [comment]
I prepare a pull request but I am not allowed to send it to the repository?

**Comment by andreassolberg** [comment]
I think is resolved in the newest version. Let me know if this still is a problem.
