### ISSUE TITLE
Make node-compatible and publish on npm

### ISSUE THREAD

**Issue by letmaik** [andreassolberg/jso#59]
It would be really cool if this library would support node-compatible packaging environments, using `module.exports`. Also, it should be published on npm. Would make it a bit easier to use if you have an npm-based workflow.

**Comment by ChrisCooney** [comment]
Seconded. This has stopped me from using the library.

**Comment by aequasi** [comment]
Hopefully this gets more visibility. This is a necessity.

**Comment by maksimu** [comment]
I agree.
Here is how I use it so far in `package.json`

```
    "jso": "git+https://github.com/andreassolberg/jso.git",
```

**Comment by andreassolberg** [comment]
I've now updated it to npm, and using ES6 syntax for loading. I've not intended to support node.js, but hopefully it would be able to load and use some of it. I'm not sure I see the use case for doing implicit grant flow in node.js though.
