### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by pidov** [andreassolberg/jso#60]
Hi,

I love the simplicity of this library and it pretty much does what I need it to do (besides some minor issue) but I'm wondering if I should go with it or look for an alternative. 

The amount of pull requests, open issues and the lack of commits make me think that @andreassolberg abandoned the project. 
So my question is wether you plan to transfer ownership (if there's an interest) or you're going to maintain the project yourself?

pidov

**Comment by andreassolberg** [comment]
Thanks for asking.

The project is not permanently abadoned. But I have not been able to prioritize following up all the requests for a while. I hope to soon reserve time to dive into the project again, to respond to requests and prepare a new major update. I'll leave this issue open until then.

I appologize for the inconvencience.

**Comment by simonv3** [comment]
Maybe it's an idea to grant someone else contributor status to deal with some of the smaller maintenance issues (for example: adding the project to npm)? I'd be happy to help with that.

**Comment by andreassolberg** [comment]
Sorry about the lack of following up this project the last few years.
I've now updated master with a es6, webpack, babel, npm friendly version.
Currently versioned `4.0.0-rc.4`.
I hope to be able to maintain the library from now on.
