### ISSUE TITLE
doing something similar to tradeking?

### ISSUE THREAD

**Issue by thaibt** [andreassolberg/jso#65]
Sorry, beginner here, I was wondering, how will i structure this to obtain a json return from this particular API?

https://developers.tradeking.com/documentation/market-toplists-get

I looked at the header requirement to have 

> 
> Authorization: OAuth
>   oauth_consumer_key="0685bd9184jfhq22",
>   oauth_token="ad180jjd733klru7",
>   oauth_signature_method="HMAC-SHA1",
>   oauth_signature="wOJIO9A2W5mFwDgiDvZbTSMK%2FPY%3D",
>   oauth_timestamp="137131200",
>   oauth_nonce="4572616e48616d6d65724c61686176",
>   oauth_version="1.0"
> 

But I am not sure how will this be converted to that ^?

**Comment by andreassolberg** [comment]
If the API is using OAuth 1.0, JSO may not help, as it implements Oauth 2.0. Oauth 1.0 is completely different.
