### ISSUE TITLE
JSO undefined

### ISSUE THREAD

**Issue by dosstx** [andreassolberg/jso#75]
When using the master branch, I get the following error:

`Uncaught ReferenceError: JSO is not defined`

I have a really simple app like so:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://unpkg.com/jso/dist/jso.js"></script>
</head>
<body>
    <h1>Hello World</h1>

    <script>

    let client = new JSO({
	providerID: "my-auth-server",
	client_id: <client id here>,
	redirect_uri: <redirect uri here>,
	authorization: <auth uri here>
});
    
    </script>
</body>
</html>
```
I am trying to troubleshoot this error before I move on with the rest of the scaffolding. Thanks.

**Comment by andreassolberg** [comment]
Check te readme example. When you se the bundne refer ti jso.JSO

Does that help?

**Comment by dosstx** [comment]
That helps. Does this look good?

```
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="./node_modules/jquery/dist/jquery.js"></script>
    <script src="./node_modules/jso/dist/jso.js"></script>
    <!-- <script type="text/javascript" src="https://unpkg.com/jso/dist/jso.js"></script> -->
    <script>
        let client = new jso.JSO({
            providerID: "google",
            client_id: "541950296471.apps.googleusercontent.com",
            redirect_uri: "http://bridge.uninett.no/jso/index.html",
            authorization: "https://accounts.google.com/o/oauth2/auth",
            scopes: { request: ["https://www.googleapis.com/auth/userinfo.profile"] }
        });
        client.callback();
        client.getToken()
            .then((token) => {
                console.log("I got the token: ", token)
            })
    </script>
```
Note: I noticed that when I used the CDN, it was loading the jso script twice according to chrome devtools, so I uncommented that out and used the local /dist/jso.js file.

**Comment by andreassolberg** [comment]
Looks good. Does it work?

Thanks for the tip about loading twice through CDN. I've not experienced that my self, but I'll check it out.

**Comment by dosstx** [comment]
It did, but your example redirect_uri is a broken link?

**Comment by andreassolberg** [comment]
The `redirect_uri` needs to be set to the URL where your script is running!

Typically, i can be `http://localhost:8080/` or similar during development.

**Comment by andreassolberg** [comment]
I updated the README.md with more information about the redirect_uri in the example. Thanks for your feedback.

**Comment by dosstx** [comment]
Thanks! Works good so far, thank you for making this plugin.

**Comment by andreassolberg** [comment]
I'm not able to reproduce the jso bundle beeing fetched twice with chrome? Do you have a live example where I can look at the source?
