### ISSUE TITLE
Error related to state with Authlete AS server

### ISSUE THREAD

**Issue by ftarlao** [andreassolberg/jso#76]
**RECENT EDIT**: it seems the problem arises when the exactly same redirect URL is loaded twice in the same browser, perhaps is this used to avoid attacks or similar? Or is this a corner case?

I'm using JSO to implement an OAuth 2 web client (user-agent client). 
The current js code is this (configuration omitted):
```


var client = new jso.JSO(config);
client.callback();

//let's check the token
var opts = {
	scopes: {
		request: ["profile"],
		require: ["profile"]
	},
        response_type: 'token'
};
client.getToken(opts).then(function(token) { console.log("I got the token: ", token); } );
```

My Authlete AS endpoint correctly redirects the browser after authorization to the redirect uri (internal demo):
`https://172.30.42.109:8889/index.html#state=584xxxxx-xxxxx-xxxxxxxxx96009&access_token=VxxxxxxxxxxxxxxxxxxxI7GxxxxxxxxfU&token_type=Bearer&expires_in=86400&scope=profile`

Both `state` and `access_token` fragments are present, but I get this error (browser is FIrefox):
> Error: Could not retrieve state
> JSO.js:112:9 value
> JSO.js:112:9 value
> JSO.js:233:10

The error is thrown in this function:
```
processTokenResponse(atoken) {
		let state
		if (atoken.state) {
			state = this.store.getState(atoken.state)
		} else {
			throw new Error("Could not get state from storage.")
		}

		if (!state) {
			throw new Error("Could not retrieve state")
		}
		if (!state.providerID) {
			throw new Error("Could not get providerid from state")
		}
		utils.log("processTokenResponse ", atoken, "")
    return this.processReceivedToken(atoken, state)
} 
```
I cannot understand the workflow in this function, I suppose IMHO there may be a bug:  you first check if the token is there in the response, in case there is.. you use the local stored version? Do I miss something? I think you should change things in this way (very simplified) to work properly:

```
processTokenResponse(atoken) {
		let state
		if (atoken.state) {
			state = atoken.state
		} else {
                        state = this.store.getState(atoken.state)
		}

		if (!state) {
			throw new Error("Could not retrieve state")
		}
		if (!state.providerID) {
			throw new Error("Could not get providerid from state")
		}
		utils.log("processTokenResponse ", atoken, "")
    return this.processReceivedToken(atoken, state)
} 
```
I have performed only a quick debug, I'm not 100% confident (and I'm not a Js developer).
Hope useful, 
Regards

**Comment by ftarlao** [comment]
In case it is not a bug but a malformed URL or ... Do I miss any detail? .. any tip would be appreciated.
Regards

**Comment by andreassolberg** [comment]
Yes, loading the redirect_uri with the same response twice SHOULD give you an error. The state parameter is bound to a single login flow, and is protected against reuse.

JSO should when processing the response, replace the hash fragment with a cached version of what was before, and then the response is removed, such that the user should not end up with accidentally reloading the response page.

**Comment by andreassolberg** [comment]
Your proposed code change will not work I think. The state is a cache object with a state parameter in the response as a lookup key. It is used to connect the request and the response for security reasons.

**Comment by ftarlao** [comment]
OK, I think I have understood now. Thank you for the clear explanations and for your OAuth library. Now I'm using it in the right way and works like intended.
Regards

**Comment by andreassolberg** [comment]
Great! have a nice day!
