### ISSUE TITLE
Do we really need `webpack-cli` dependency?

### ISSUE THREAD

**Issue by delissonjunio** [andreassolberg/jso#80]
I see that the library currently has a dependency (not a dev-dependency) on `webpack-cli`. Adding this package to our repo has added together more than a thousand lines and many packages to our lockfile/node_modules directory.

I don't immediately see a need for such a dependency, is that really needed or can we get rid of it? Maybe change it to a dev-dependency?

**Comment by andreassolberg** [comment]
I agree!
